version: '3.8'

services:
  # Aplicação Flask
  cotacoes-api:
    build: .
    container_name: cotacoes-api
    ports:
      - "5000:5000"
    environment:
      # Configurações da aplicação
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Volume para logs (opcional)
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - cotacoes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cotacoes-api.rule=Host(`localhost`)"

  # Nginx para servir arquivos estáticos (opcional, para produção)
  nginx:
    image: nginx:alpine
    container_name: cotacoes-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - cotacoes-api
    restart: unless-stopped
    networks:
      - cotacoes-network
    profiles:
      - production

  # Redis para cache (opcional, para implementações futuras)
  redis:
    image: redis:7-alpine
    container_name: cotacoes-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - cotacoes-network
    profiles:
      - cache

networks:
  cotacoes-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
